# Site Info
baseURL: "https://elvisfinol.github.io/blog/"
languageCode: "en-us"
title: "elvisfinol-blog"
theme: "PaperMod"

#Enable comments by entering your disqus shortname
disqusShortname: elvisfinol

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ExampleSite
    description: "ExampleSite description"
    author: Elvis Finol    

    images: ["<link or path of image for opengraph, twitter-cards>"]

    ShowReadingTime: true
    ShowShareButtons: false
    comments: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false

    assets:
        # disableHLJS: true # to disable highlightjs
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        # icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Hello!
        imageUrl: "https://images.unsplash.com/photo-1580777361964-27e9cdd2f838?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hello \U0001F44B"
        Content: Welcome board! Here you will see topics about new tech and guides about what I am learning at the moment. Enjoy the stay! 

    socialIcons:
        - name: email
          url: "mailto:e.finol@gmail.com"
        - name: linkedin
          url: "https://www.linkedin.com/in/elvisfinol/"
        - name: github
          url: "https://github.com/elvisfinol"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

# Menu feature
menu:
    main: 
        - identifier: archive
          name: archives
          url: /archive/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identified: search
          name: 🔍
          url: /search/
          weight: 30

# Search feature
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
